/*------------------------
   MENUDEMO.H header file
  ------------------------*/

#define IDM_NORD             1
#define IDM_SUD              2
#define IDM_EST              3
#define IDM_OVEST            4
#define IDM_PERENNE          5
#define IDM_FERMA            6
#define IDM_EXIT             7

#define IDM_PARALLELI       10
#define IDM_MERIDIANI       11
#define IDM_FUSIORARI       12
#define IDM_TROPICI         13
#define IDM_CIRCOLI         14
#define IDM_EQUATORE        15
#define IDM_GREENWICH       16

#define IDM_LONGLAT         20
#define IDM_AVVICINAMENTO   21
#define IDM_ALLONTANAMENTO  22
#define IDM_RIPRISTINO      23

#define IDM_ABOUT           30

#define IDC_EDIT1			2001
#define IDC_EDIT2			2002
